# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/nikita/Documents/network/project_aiosmtpd/project_aiosmtpd/outbox.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 382)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.windowlogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.windowlogoLabel.setObjectName("windowlogoLabel")
        self.gridLayout.addWidget(self.windowlogoLabel, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 2, 1, 1)
        self.showButton = QtWidgets.QPushButton(self.centralwidget)
        self.showButton.setObjectName("showButton")
        self.gridLayout.addWidget(self.showButton, 1, 3, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 2, 0, 1, 4)
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setObjectName("quitButton")
        self.gridLayout.addWidget(self.quitButton, 3, 0, 1, 1)
        self.expandButton = QtWidgets.QPushButton(self.centralwidget)
        self.expandButton.setObjectName("expandButton")
        self.gridLayout.addWidget(self.expandButton, 3, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_mail = QtWidgets.QAction(MainWindow)
        self.actionNew_mail.setObjectName("actionNew_mail")
        self.actionInbox = QtWidgets.QAction(MainWindow)
        self.actionInbox.setObjectName("actionInbox")
        self.actionOutbox = QtWidgets.QAction(MainWindow)
        self.actionOutbox.setObjectName("actionOutbox")
        self.actionSource_code = QtWidgets.QAction(MainWindow)
        self.actionSource_code.setObjectName("actionSource_code")
        self.actionPresentation = QtWidgets.QAction(MainWindow)
        self.actionPresentation.setObjectName("actionPresentation")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.menuFile.addAction(self.actionNew_mail)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionInbox)
        self.menuFile.addAction(self.actionOutbox)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLogout)
        self.menuAbout.addAction(self.actionSource_code)
        self.menuAbout.addAction(self.actionPresentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.windowlogoLabel.setText(_translate("MainWindow", "Username Outbox"))
        self.label.setText(_translate("MainWindow", "Select amount of most recent messages to be shown:"))
        self.showButton.setText(_translate("MainWindow", "Show"))
        self.quitButton.setText(_translate("MainWindow", "Quit"))
        self.expandButton.setText(_translate("MainWindow", "Expand"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionNew_mail.setText(_translate("MainWindow", "New mail"))
        self.actionInbox.setText(_translate("MainWindow", "Inbox"))
        self.actionOutbox.setText(_translate("MainWindow", "Outbox"))
        self.actionSource_code.setText(_translate("MainWindow", "Source code"))
        self.actionPresentation.setText(_translate("MainWindow", "Presentation"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))

